export const permissions = [
  "createDeveloper",
  "updateDeveloper",
  "deleteDeveloper",
  "postApartment",
  "updateApartment",
  "deleteApartment",
  "getLeads",
  "createLead",
  "updateLead",
  "deleteLead",
  "createProject",
  "updateProject",
  "deleteProject",
  "createRole",
  "deleteRole",
  "viewDeletedData",
];
